cria zip para lambda

diff --git a/.github/workflows/apply.yml b/.github/workflows/apply.yml
--- a/.github/workflows/apply.yml
+++ b/.github/workflows/apply.yml
@@ -47,6 +47,14 @@ jobs:
           zip -r ../../modules/lambda/zips/fastfood-auth-lambda.zip .
           cd -
 
+      - name: Verify Lambda ZIPs exist
+        run: |
+          echo "PWD:"
+          pwd
+          echo "Listing modules/lambda/zips:"
+          ls -lh modules/lambda/zips || echo "ZIP DIRECTORY NOT FOUND"
+
+
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
@@ -83,6 +91,38 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: ${{ vars.NODE_VERSION }}
+
+      - name: Install Node.js dependencies for login_lambda
+        working-directory: ./lambdas/login_lambda
+        run: npm install
+
+      - name: Install Node.js dependencies for auth_lambda
+        working-directory: ./lambdas/auth_lambda
+        run: npm install
+
+      - name: Create Lambda ZIP packages
+        run: |
+          mkdir -p modules/lambda/zips
+
+          cd lambdas/login_lambda
+          zip -r ../../modules/lambda/zips/fastfood-login-lambda.zip .
+          cd -
+
+          cd lambdas/auth_lambda
+          zip -r ../../modules/lambda/zips/fastfood-auth-lambda.zip .
+          cd -
+
+      - name: Verify Lambda ZIPs exist
+        run: |
+          echo "PWD:"
+          pwd
+          echo "Listing modules/lambda/zips:"
+          ls -lh modules/lambda/zips || echo "ZIP DIRECTORY NOT FOUND"
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v2
